
import java.awt.Color;
import java.awt.Container;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anshu
 */
public class FeedAdd extends javax.swing.JFrame {
Connection con;  
PreparedStatement pst;

    /**
     * Creates new form FeedAdd
     */
    public FeedAdd() {
        Container c = getContentPane();
        c.setBackground(new Color(228, 240, 252));
        initComponents();
        try {
      
        setVisible(true);
        Class.forName("com.mysql.cj.jdbc.Driver"); //1.driver 
        con=DriverManager.getConnection("jdbc:mysql://db4free.net:3306/feedadddb","feedadd","dbpass123"); //connection string
        JOptionPane.showMessageDialog(null,"DataBase Connected");
         //sql query 
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jRadioButton49 = new javax.swing.JRadioButton();
        jRadioButton50 = new javax.swing.JRadioButton();
        jRadioButton52 = new javax.swing.JRadioButton();
        jRadioButton53 = new javax.swing.JRadioButton();
        jRadioButton54 = new javax.swing.JRadioButton();
        jRadioButton51 = new javax.swing.JRadioButton();
        jRadioButton55 = new javax.swing.JRadioButton();
        jRadioButton56 = new javax.swing.JRadioButton();
        jRadioButton57 = new javax.swing.JRadioButton();
        jRadioButton58 = new javax.swing.JRadioButton();
        jRadioButton64 = new javax.swing.JRadioButton();
        jRadioButton65 = new javax.swing.JRadioButton();
        jRadioButton66 = new javax.swing.JRadioButton();
        jRadioButton67 = new javax.swing.JRadioButton();
        jRadioButton68 = new javax.swing.JRadioButton();
        jRadioButton69 = new javax.swing.JRadioButton();
        jRadioButton70 = new javax.swing.JRadioButton();
        jRadioButton71 = new javax.swing.JRadioButton();
        jRadioButton72 = new javax.swing.JRadioButton();
        jRadioButton73 = new javax.swing.JRadioButton();
        jRadioButton74 = new javax.swing.JRadioButton();
        jRadioButton75 = new javax.swing.JRadioButton();
        jRadioButton76 = new javax.swing.JRadioButton();
        jRadioButton77 = new javax.swing.JRadioButton();
        jRadioButton78 = new javax.swing.JRadioButton();
        jRadioButton79 = new javax.swing.JRadioButton();
        jRadioButton80 = new javax.swing.JRadioButton();
        jRadioButton81 = new javax.swing.JRadioButton();
        jRadioButton82 = new javax.swing.JRadioButton();
        jRadioButton83 = new javax.swing.JRadioButton();
        jRadioButton84 = new javax.swing.JRadioButton();
        jRadioButton85 = new javax.swing.JRadioButton();
        jRadioButton86 = new javax.swing.JRadioButton();
        jRadioButton87 = new javax.swing.JRadioButton();
        jRadioButton88 = new javax.swing.JRadioButton();
        jRadioButton89 = new javax.swing.JRadioButton();
        jRadioButton90 = new javax.swing.JRadioButton();
        jRadioButton91 = new javax.swing.JRadioButton();
        jRadioButton92 = new javax.swing.JRadioButton();
        jRadioButton93 = new javax.swing.JRadioButton();
        jRadioButton94 = new javax.swing.JRadioButton();
        jRadioButton95 = new javax.swing.JRadioButton();
        jRadioButton96 = new javax.swing.JRadioButton();
        jRadioButton97 = new javax.swing.JRadioButton();
        jRadioButton98 = new javax.swing.JRadioButton();
        jRadioButton99 = new javax.swing.JRadioButton();
        jRadioButton100 = new javax.swing.JRadioButton();
        jRadioButton101 = new javax.swing.JRadioButton();
        jRadioButton102 = new javax.swing.JRadioButton();
        jRadioButton103 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Department");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Semester");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Teacher/Subject");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setText("Rating/Subjects");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel6.setText("1 Excellent");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel7.setText("2 Very Good");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel8.setText("3 Good");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel9.setText("4 Average");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel10.setText("5 Below Average");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setText("Punctuality in the Class");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setText("Completes syllabus of the course in time");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setText("Regularity in taking Classes");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setText("Scheduled organization of assignments, class test, quizzes and seminars");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel15.setText("Self-confidence");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel16.setText("Communication skills");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel17.setText("Teaching the subject matter");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel18.setText("Helps student in providing study material ");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel19.setText("Helps students in realizing career goals");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel20.setText("Helps students in realizing their strengths and developmental needs");

        jRadioButton49.setText("1");
        jRadioButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton49ActionPerformed(evt);
            }
        });

        jRadioButton50.setText("2");

        jRadioButton52.setText("3");

        jRadioButton53.setText("4");

        jRadioButton54.setText("5");
        jRadioButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton54ActionPerformed(evt);
            }
        });

        jRadioButton51.setText("1");
        jRadioButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton51ActionPerformed(evt);
            }
        });

        jRadioButton55.setText("2");

        jRadioButton56.setText("3");

        jRadioButton57.setText("4");

        jRadioButton58.setText("5");
        jRadioButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton58ActionPerformed(evt);
            }
        });

        jRadioButton64.setText("1");
        jRadioButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton64ActionPerformed(evt);
            }
        });

        jRadioButton65.setText("2");

        jRadioButton66.setText("3");

        jRadioButton67.setText("4");

        jRadioButton68.setText("5");
        jRadioButton68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton68ActionPerformed(evt);
            }
        });

        jRadioButton69.setText("1");
        jRadioButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton69ActionPerformed(evt);
            }
        });

        jRadioButton70.setText("2");

        jRadioButton71.setText("3");

        jRadioButton72.setText("4");

        jRadioButton73.setText("5");
        jRadioButton73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton73ActionPerformed(evt);
            }
        });

        jRadioButton74.setText("1");
        jRadioButton74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton74ActionPerformed(evt);
            }
        });

        jRadioButton75.setText("2");

        jRadioButton76.setText("3");

        jRadioButton77.setText("4");

        jRadioButton78.setText("5");
        jRadioButton78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton78ActionPerformed(evt);
            }
        });

        jRadioButton79.setText("1");
        jRadioButton79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton79ActionPerformed(evt);
            }
        });

        jRadioButton80.setText("2");

        jRadioButton81.setText("3");

        jRadioButton82.setText("4");

        jRadioButton83.setText("5");
        jRadioButton83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton83ActionPerformed(evt);
            }
        });

        jRadioButton84.setText("1");
        jRadioButton84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton84ActionPerformed(evt);
            }
        });

        jRadioButton85.setText("2");

        jRadioButton86.setText("3");

        jRadioButton87.setText("4");

        jRadioButton88.setText("5");
        jRadioButton88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton88ActionPerformed(evt);
            }
        });

        jRadioButton89.setText("1");
        jRadioButton89.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton89ActionPerformed(evt);
            }
        });

        jRadioButton90.setText("2");

        jRadioButton91.setText("3");

        jRadioButton92.setText("4");

        jRadioButton93.setText("5");
        jRadioButton93.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton93ActionPerformed(evt);
            }
        });

        jRadioButton94.setText("1");
        jRadioButton94.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton94ActionPerformed(evt);
            }
        });

        jRadioButton95.setText("2");

        jRadioButton96.setText("3");

        jRadioButton97.setText("4");

        jRadioButton98.setText("5");
        jRadioButton98.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton98ActionPerformed(evt);
            }
        });

        jRadioButton99.setText("1");
        jRadioButton99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton99ActionPerformed(evt);
            }
        });

        jRadioButton100.setText("2");

        jRadioButton101.setText("3");

        jRadioButton102.setText("4");

        jRadioButton103.setText("5");
        jRadioButton103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton103ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ETC", "IT", "CSE", "ME", "EE", "CE" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I", "II", "III", "IV", "V", "VI", "VII", "VIII" }));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Description :-");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("Enrollment No.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel5)
                .addGap(167, 167, 167)
                .addComponent(jLabel6)
                .addGap(44, 44, 44)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel9)
                .addGap(27, 27, 27)
                .addComponent(jLabel10))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249)
                .addComponent(jRadioButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jRadioButton50)
                .addGap(61, 61, 61)
                .addComponent(jRadioButton52)
                .addGap(57, 57, 57)
                .addComponent(jRadioButton53)
                .addGap(79, 79, 79)
                .addComponent(jRadioButton54))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197)
                .addComponent(jRadioButton51, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jRadioButton55)
                .addGap(61, 61, 61)
                .addComponent(jRadioButton56)
                .addGap(57, 57, 57)
                .addComponent(jRadioButton57)
                .addGap(79, 79, 79)
                .addComponent(jRadioButton58))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jRadioButton64, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jRadioButton65)
                .addGap(61, 61, 61)
                .addComponent(jRadioButton66)
                .addGap(58, 58, 58)
                .addComponent(jRadioButton67)
                .addGap(78, 78, 78)
                .addComponent(jRadioButton68))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton69, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jRadioButton70)
                .addGap(61, 61, 61)
                .addComponent(jRadioButton71)
                .addGap(58, 58, 58)
                .addComponent(jRadioButton72)
                .addGap(78, 78, 78)
                .addComponent(jRadioButton73))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(jRadioButton74, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jRadioButton75)
                .addGap(61, 61, 61)
                .addComponent(jRadioButton76)
                .addGap(58, 58, 58)
                .addComponent(jRadioButton77)
                .addGap(78, 78, 78)
                .addComponent(jRadioButton78))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192)
                .addComponent(jRadioButton89, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jRadioButton90)
                .addGap(61, 61, 61)
                .addComponent(jRadioButton91)
                .addGap(58, 58, 58)
                .addComponent(jRadioButton92)
                .addGap(78, 78, 78)
                .addComponent(jRadioButton93))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177)
                .addComponent(jRadioButton84, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jRadioButton85)
                .addGap(61, 61, 61)
                .addComponent(jRadioButton86)
                .addGap(58, 58, 58)
                .addComponent(jRadioButton87)
                .addGap(78, 78, 78)
                .addComponent(jRadioButton88))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(jRadioButton94, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jRadioButton95)
                .addGap(61, 61, 61)
                .addComponent(jRadioButton96)
                .addGap(58, 58, 58)
                .addComponent(jRadioButton97)
                .addGap(78, 78, 78)
                .addComponent(jRadioButton98))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jRadioButton79, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jRadioButton80)
                .addGap(61, 61, 61)
                .addComponent(jRadioButton81)
                .addGap(58, 58, 58)
                .addComponent(jRadioButton82)
                .addGap(78, 78, 78)
                .addComponent(jRadioButton83))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jRadioButton99, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jRadioButton100)
                .addGap(61, 61, 61)
                .addComponent(jRadioButton101)
                .addGap(58, 58, 58)
                .addComponent(jRadioButton102)
                .addGap(78, 78, 78)
                .addComponent(jRadioButton103))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(435, 435, 435)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel21)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4)))
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel11))
                    .addComponent(jRadioButton49)
                    .addComponent(jRadioButton50)
                    .addComponent(jRadioButton52)
                    .addComponent(jRadioButton53)
                    .addComponent(jRadioButton54))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel13))
                    .addComponent(jRadioButton51)
                    .addComponent(jRadioButton55)
                    .addComponent(jRadioButton56)
                    .addComponent(jRadioButton57)
                    .addComponent(jRadioButton58))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel12))
                    .addComponent(jRadioButton64)
                    .addComponent(jRadioButton65)
                    .addComponent(jRadioButton66)
                    .addComponent(jRadioButton67)
                    .addComponent(jRadioButton68))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel14))
                    .addComponent(jRadioButton69)
                    .addComponent(jRadioButton70)
                    .addComponent(jRadioButton71)
                    .addComponent(jRadioButton72)
                    .addComponent(jRadioButton73))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel15))
                    .addComponent(jRadioButton74)
                    .addComponent(jRadioButton75)
                    .addComponent(jRadioButton76)
                    .addComponent(jRadioButton77)
                    .addComponent(jRadioButton78))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel16))
                    .addComponent(jRadioButton89)
                    .addComponent(jRadioButton90)
                    .addComponent(jRadioButton91)
                    .addComponent(jRadioButton92)
                    .addComponent(jRadioButton93))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel17))
                    .addComponent(jRadioButton84)
                    .addComponent(jRadioButton85)
                    .addComponent(jRadioButton86)
                    .addComponent(jRadioButton87)
                    .addComponent(jRadioButton88))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel18))
                    .addComponent(jRadioButton94)
                    .addComponent(jRadioButton95)
                    .addComponent(jRadioButton96)
                    .addComponent(jRadioButton97)
                    .addComponent(jRadioButton98))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel19))
                    .addComponent(jRadioButton79)
                    .addComponent(jRadioButton80)
                    .addComponent(jRadioButton81)
                    .addComponent(jRadioButton82)
                    .addComponent(jRadioButton83))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel20))
                    .addComponent(jRadioButton99)
                    .addComponent(jRadioButton100)
                    .addComponent(jRadioButton101)
                    .addComponent(jRadioButton102)
                    .addComponent(jRadioButton103))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton49ActionPerformed

    private void jRadioButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton54ActionPerformed

    private void jRadioButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton51ActionPerformed

    private void jRadioButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton58ActionPerformed

    private void jRadioButton69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton69ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton69ActionPerformed

    private void jRadioButton73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton73ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton73ActionPerformed

    private void jRadioButton74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton74ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton74ActionPerformed

    private void jRadioButton78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton78ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton78ActionPerformed

    private void jRadioButton79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton79ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton79ActionPerformed

    private void jRadioButton83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton83ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton83ActionPerformed

    private void jRadioButton84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton84ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton84ActionPerformed

    private void jRadioButton88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton88ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton88ActionPerformed

    private void jRadioButton89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton89ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton89ActionPerformed

    private void jRadioButton93ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton93ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton93ActionPerformed

    private void jRadioButton94ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton94ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton94ActionPerformed

    private void jRadioButton98ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton98ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton98ActionPerformed

    private void jRadioButton99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton99ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton99ActionPerformed

    private void jRadioButton103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton103ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton103ActionPerformed

    private void jRadioButton68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton68ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton68ActionPerformed

    private void jRadioButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton64ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String sub = null;
//for first subject
if(jRadioButton49.isSelected())
{
    sub = "1";
jRadioButton50.setEnabled(false);
jRadioButton52.setEnabled(false);
jRadioButton53.setEnabled(false);
jRadioButton54.setEnabled(false);

}
else if(jRadioButton50.isSelected())
{
    sub = "2";
jRadioButton49.setEnabled(false);
jRadioButton52.setEnabled(false);
jRadioButton53.setEnabled(false);
jRadioButton54.setEnabled(false);

}
else if(jRadioButton52.isSelected())
{
    sub = "3";
jRadioButton49.setEnabled(false);
jRadioButton50.setEnabled(false);
jRadioButton53.setEnabled(false);
jRadioButton54.setEnabled(false);

}
else if(jRadioButton53.isSelected())
{
    sub = "4";
jRadioButton49.setEnabled(false);
jRadioButton50.setEnabled(false);
jRadioButton52.setEnabled(false);
jRadioButton54.setEnabled(false);

}
else if(jRadioButton54.isSelected())
{
    sub = "5";
jRadioButton49.setEnabled(false);
jRadioButton50.setEnabled(false);
jRadioButton52.setEnabled(false);
jRadioButton53.setEnabled(false);

}
String subject1 = sub;
// second subject

if(jRadioButton51.isSelected())
{
    sub = "1";
jRadioButton55.setEnabled(false);
jRadioButton56.setEnabled(false);
jRadioButton57.setEnabled(false);
jRadioButton58.setEnabled(false);

}
else if(jRadioButton55.isSelected())
{
    sub = "2";
jRadioButton51.setEnabled(false);
jRadioButton56.setEnabled(false);
jRadioButton57.setEnabled(false);
jRadioButton58.setEnabled(false);

}
else if(jRadioButton56.isSelected())
{
    sub = "3";
jRadioButton51.setEnabled(false);
jRadioButton55.setEnabled(false);
jRadioButton57.setEnabled(false);
jRadioButton58.setEnabled(false);

}
else if(jRadioButton57.isSelected())
{
    sub = "4";
jRadioButton51.setEnabled(false);
jRadioButton55.setEnabled(false);
jRadioButton56.setEnabled(false);
jRadioButton58.setEnabled(false);

}
else if(jRadioButton58.isSelected())
{
    sub = "5";
jRadioButton51.setEnabled(false);
jRadioButton55.setEnabled(false);
jRadioButton56.setEnabled(false);
jRadioButton57.setEnabled(false);

}
String subject2 = sub;

//third subject

if(jRadioButton64.isSelected())
{
    sub = "1";
jRadioButton65.setEnabled(false);
jRadioButton66.setEnabled(false);
jRadioButton67.setEnabled(false);
jRadioButton68.setEnabled(false);

}
else if(jRadioButton65.isSelected())
{
    sub = "2";
jRadioButton64.setEnabled(false);
jRadioButton66.setEnabled(false);
jRadioButton67.setEnabled(false);
jRadioButton68.setEnabled(false);

}
else if(jRadioButton66.isSelected())
{
    sub = "3";
jRadioButton64.setEnabled(false);
jRadioButton65.setEnabled(false);
jRadioButton67.setEnabled(false);
jRadioButton68.setEnabled(false);

}
else if(jRadioButton67.isSelected())
{
    sub = "4";
jRadioButton64.setEnabled(false);
jRadioButton65.setEnabled(false);
jRadioButton66.setEnabled(false);
jRadioButton68.setEnabled(false);

}
else if(jRadioButton68.isSelected())
{
    sub = "5";
jRadioButton64.setEnabled(false);
jRadioButton65.setEnabled(false);
jRadioButton66.setEnabled(false);
jRadioButton67.setEnabled(false);

}
String subject3 = sub;

//fourth subject

if(jRadioButton69.isSelected())
{
    sub = "1";
jRadioButton70.setEnabled(false);
jRadioButton71.setEnabled(false);
jRadioButton72.setEnabled(false);
jRadioButton73.setEnabled(false);

}
else if(jRadioButton70.isSelected())
{
    sub = "2";
jRadioButton69.setEnabled(false);
jRadioButton71.setEnabled(false);
jRadioButton72.setEnabled(false);
jRadioButton73.setEnabled(false);

}
else if(jRadioButton71.isSelected())
{
    sub = "3";
jRadioButton69.setEnabled(false);
jRadioButton70.setEnabled(false);
jRadioButton72.setEnabled(false);
jRadioButton73.setEnabled(false);

}
else if(jRadioButton72.isSelected())
{
    sub = "4";
jRadioButton69.setEnabled(false);
jRadioButton70.setEnabled(false);
jRadioButton71.setEnabled(false);
jRadioButton73.setEnabled(false);

}
else if(jRadioButton73.isSelected())
{
    sub = "5";
jRadioButton69.setEnabled(false);
jRadioButton70.setEnabled(false);
jRadioButton71.setEnabled(false);
jRadioButton72.setEnabled(false);

}
String subject4 = sub;


//fifth subject

if(jRadioButton74.isSelected())
{
    sub = "1";
jRadioButton75.setEnabled(false);
jRadioButton76.setEnabled(false);
jRadioButton77.setEnabled(false);
jRadioButton78.setEnabled(false);

}
else if(jRadioButton75.isSelected())
{
    sub = "2";
jRadioButton74.setEnabled(false);
jRadioButton76.setEnabled(false);
jRadioButton77.setEnabled(false);
jRadioButton78.setEnabled(false);

}
else if(jRadioButton76.isSelected())
{
    sub = "3";
jRadioButton74.setEnabled(false);
jRadioButton75.setEnabled(false);
jRadioButton77.setEnabled(false);
jRadioButton78.setEnabled(false);

}
else if(jRadioButton77.isSelected())
{
    sub = "4";
jRadioButton74.setEnabled(false);
jRadioButton75.setEnabled(false);
jRadioButton76.setEnabled(false);
jRadioButton78.setEnabled(false);

}
else if(jRadioButton78.isSelected())
{
    sub = "5";
jRadioButton74.setEnabled(false);
jRadioButton75.setEnabled(false);
jRadioButton76.setEnabled(false);
jRadioButton77.setEnabled(false);

}
String subject5 = sub;


//sixth subject


if(jRadioButton89.isSelected())
{
    sub = "1";
jRadioButton90.setEnabled(false);
jRadioButton91.setEnabled(false);
jRadioButton92.setEnabled(false);
jRadioButton93.setEnabled(false);

}
else if(jRadioButton90.isSelected())
{
    sub = "2";
jRadioButton89.setEnabled(false);
jRadioButton91.setEnabled(false);
jRadioButton92.setEnabled(false);
jRadioButton93.setEnabled(false);

}
else if(jRadioButton91.isSelected())
{
    sub = "3";
jRadioButton89.setEnabled(false);
jRadioButton90.setEnabled(false);
jRadioButton92.setEnabled(false);
jRadioButton93.setEnabled(false);

}
else if(jRadioButton92.isSelected())
{
    sub = "4";
jRadioButton89.setEnabled(false);
jRadioButton90.setEnabled(false);
jRadioButton91.setEnabled(false);
jRadioButton93.setEnabled(false);

}
else if(jRadioButton93.isSelected())
{
    sub = "5";
jRadioButton89.setEnabled(false);
jRadioButton90.setEnabled(false);
jRadioButton91.setEnabled(false);
jRadioButton92.setEnabled(false);

}
String subject6 = sub;


//seventh subjects


if(jRadioButton84.isSelected())
{
    sub = "1";
jRadioButton85.setEnabled(false);
jRadioButton86.setEnabled(false);
jRadioButton87.setEnabled(false);
jRadioButton88.setEnabled(false);

}
else if(jRadioButton85.isSelected())
{
    sub = "2";
jRadioButton84.setEnabled(false);
jRadioButton86.setEnabled(false);
jRadioButton87.setEnabled(false);
jRadioButton88.setEnabled(false);

}
else if(jRadioButton86.isSelected())
{
    sub = "3";
jRadioButton84.setEnabled(false);
jRadioButton85.setEnabled(false);
jRadioButton87.setEnabled(false);
jRadioButton88.setEnabled(false);

}
else if(jRadioButton87.isSelected())
{
    sub = "4";
jRadioButton84.setEnabled(false);
jRadioButton85.setEnabled(false);
jRadioButton86.setEnabled(false);
jRadioButton88.setEnabled(false);

}
else if(jRadioButton88.isSelected())
{
    sub = "5";
jRadioButton84.setEnabled(false);
jRadioButton85.setEnabled(false);
jRadioButton86.setEnabled(false);
jRadioButton87.setEnabled(false);

}String subject7 = sub;



//eight subject


if(jRadioButton94.isSelected())
{
    sub = "1";
jRadioButton95.setEnabled(false);
jRadioButton96.setEnabled(false);
jRadioButton97.setEnabled(false);
jRadioButton98.setEnabled(false);

}
else if(jRadioButton95.isSelected())
{
    sub = "2";
jRadioButton94.setEnabled(false);
jRadioButton96.setEnabled(false);
jRadioButton97.setEnabled(false);
jRadioButton98.setEnabled(false);

}
else if(jRadioButton96.isSelected())
{
    sub = "3";
jRadioButton94.setEnabled(false);
jRadioButton95.setEnabled(false);
jRadioButton97.setEnabled(false);
jRadioButton98.setEnabled(false);

}
else if(jRadioButton97.isSelected())
{
    sub = "4";
jRadioButton94.setEnabled(false);
jRadioButton95.setEnabled(false);
jRadioButton96.setEnabled(false);
jRadioButton98.setEnabled(false);

}
else if(jRadioButton98.isSelected())
{
    sub = "5";
jRadioButton94.setEnabled(false);
jRadioButton95.setEnabled(false);
jRadioButton96.setEnabled(false);
jRadioButton97.setEnabled(false);

}
String subject8 = sub;


//ninth subject


if(jRadioButton79.isSelected())
{
    sub = "1";
jRadioButton80.setEnabled(false);
jRadioButton81.setEnabled(false);
jRadioButton82.setEnabled(false);
jRadioButton83.setEnabled(false);

}
else if(jRadioButton80.isSelected())
{
    sub = "2";
jRadioButton79.setEnabled(false);
jRadioButton81.setEnabled(false);
jRadioButton82.setEnabled(false);
jRadioButton83.setEnabled(false);

}
else if(jRadioButton81.isSelected())
{
    sub = "3";
jRadioButton79.setEnabled(false);
jRadioButton80.setEnabled(false);
jRadioButton82.setEnabled(false);
jRadioButton83.setEnabled(false);

}
else if(jRadioButton82.isSelected())
{
    sub = "4";
jRadioButton80.setEnabled(false);
jRadioButton81.setEnabled(false);
jRadioButton79.setEnabled(false);
jRadioButton83.setEnabled(false);

}
else if(jRadioButton83.isSelected())
{
    sub = "5";
jRadioButton80.setEnabled(false);
jRadioButton81.setEnabled(false);
jRadioButton82.setEnabled(false);
jRadioButton79.setEnabled(false);

}

String subject9 = sub;


//tenth subject


if(jRadioButton99.isSelected())
{
    sub = "1";
jRadioButton100.setEnabled(false);
jRadioButton101.setEnabled(false);
jRadioButton102.setEnabled(false);
jRadioButton103.setEnabled(false);

}
else if(jRadioButton100.isSelected())
{
    sub = "2";
jRadioButton99.setEnabled(false);
jRadioButton101.setEnabled(false);
jRadioButton102.setEnabled(false);
jRadioButton103.setEnabled(false);

}
else if(jRadioButton101.isSelected())
{
    sub = "3";
jRadioButton100.setEnabled(false);
jRadioButton99.setEnabled(false);
jRadioButton102.setEnabled(false);
jRadioButton103.setEnabled(false);

}
else if(jRadioButton102.isSelected())
{
    sub = "4";
jRadioButton100.setEnabled(false);
jRadioButton101.setEnabled(false);
jRadioButton99.setEnabled(false);
jRadioButton103.setEnabled(false);

}
else if(jRadioButton103.isSelected())
{
    sub = "5";
jRadioButton100.setEnabled(false);
jRadioButton101.setEnabled(false);
jRadioButton102.setEnabled(false);
jRadioButton99.setEnabled(false);

}String subject10 = sub;



 
     
    
    
    String roll = jTextField2.getText();
    String semester = (String) jComboBox4.getSelectedItem();
    String branch = (String) jComboBox3.getSelectedItem();
    String teacher_name = jTextField1.getText();
   
     
     String description = jTextArea1.getText();
     
       
    String query = "insert into feedback values ('"+roll+"','"+semester+"','"+branch+"','"+teacher_name+"','"+subject1+"','"+subject2+"','"+subject3+"','"+subject4+"','"+subject5+"','"+subject6+"','"+subject7+"','"+subject8+"','"+subject9+"','"+subject10+"','"+description+"')";
   


    try {
        Class.forName("com.mysql.cj.jdbc.Driver"); //1.driver 
        con=DriverManager.getConnection("jdbc:mysql://db4free.net:3306/feedadddb","feedadd","dbpass123"); //connection string
        Connection c = con;
        Statement stmt = c.createStatement();
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(this, "Thankyou for your Feedback");
        setVisible(false);
        new HomeScreen().setVisible(true);
    }
    catch (HeadlessException | SQLException e)
        {
           JOptionPane.showMessageDialog(null,e.getMessage());     } catch (ClassNotFoundException ex) {
        Logger.getLogger(FeedAdd.class.getName()).log(Level.SEVERE, null, ex);
    }


      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeedAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeedAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeedAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeedAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeedAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton100;
    private javax.swing.JRadioButton jRadioButton101;
    private javax.swing.JRadioButton jRadioButton102;
    private javax.swing.JRadioButton jRadioButton103;
    private javax.swing.JRadioButton jRadioButton49;
    private javax.swing.JRadioButton jRadioButton50;
    private javax.swing.JRadioButton jRadioButton51;
    private javax.swing.JRadioButton jRadioButton52;
    private javax.swing.JRadioButton jRadioButton53;
    private javax.swing.JRadioButton jRadioButton54;
    private javax.swing.JRadioButton jRadioButton55;
    private javax.swing.JRadioButton jRadioButton56;
    private javax.swing.JRadioButton jRadioButton57;
    private javax.swing.JRadioButton jRadioButton58;
    private javax.swing.JRadioButton jRadioButton64;
    private javax.swing.JRadioButton jRadioButton65;
    private javax.swing.JRadioButton jRadioButton66;
    private javax.swing.JRadioButton jRadioButton67;
    private javax.swing.JRadioButton jRadioButton68;
    private javax.swing.JRadioButton jRadioButton69;
    private javax.swing.JRadioButton jRadioButton70;
    private javax.swing.JRadioButton jRadioButton71;
    private javax.swing.JRadioButton jRadioButton72;
    private javax.swing.JRadioButton jRadioButton73;
    private javax.swing.JRadioButton jRadioButton74;
    private javax.swing.JRadioButton jRadioButton75;
    private javax.swing.JRadioButton jRadioButton76;
    private javax.swing.JRadioButton jRadioButton77;
    private javax.swing.JRadioButton jRadioButton78;
    private javax.swing.JRadioButton jRadioButton79;
    private javax.swing.JRadioButton jRadioButton80;
    private javax.swing.JRadioButton jRadioButton81;
    private javax.swing.JRadioButton jRadioButton82;
    private javax.swing.JRadioButton jRadioButton83;
    private javax.swing.JRadioButton jRadioButton84;
    private javax.swing.JRadioButton jRadioButton85;
    private javax.swing.JRadioButton jRadioButton86;
    private javax.swing.JRadioButton jRadioButton87;
    private javax.swing.JRadioButton jRadioButton88;
    private javax.swing.JRadioButton jRadioButton89;
    private javax.swing.JRadioButton jRadioButton90;
    private javax.swing.JRadioButton jRadioButton91;
    private javax.swing.JRadioButton jRadioButton92;
    private javax.swing.JRadioButton jRadioButton93;
    private javax.swing.JRadioButton jRadioButton94;
    private javax.swing.JRadioButton jRadioButton95;
    private javax.swing.JRadioButton jRadioButton96;
    private javax.swing.JRadioButton jRadioButton97;
    private javax.swing.JRadioButton jRadioButton98;
    private javax.swing.JRadioButton jRadioButton99;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
